version: '3'

services:
  postgresql:
    image: postgres:12.2
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ExpenseSaver
      - POSTGRES_USER=postgres
    restart: always
    volumes:
      - my-db:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  my-db:
